### ISSUE TITLE
Validator does not exit cleanly

### ISSUE THREAD

**Issue by dapplion** [dappnode/DAppNodePackage-prysm#16]
When stopping the validator container it does not exit with code 0 (Version: 0.1.12 - v1.1.0 upstream). This is an issue because it will show as "CRASHED" in the UI if it does not exit with code 0
![Screenshot from 2021-01-20 13-04-10](https://user-images.githubusercontent.com/35266934/105172971-a75e7a80-5b20-11eb-941e-9b4c0a7c0e7a.png)

Validator container logs when stopping it (exit code 1)
```
time="2021-01-20 12:03:00" level=info msg="Got interrupt, shutting down..." prefix=node
time="2021-01-20 12:03:00" level=info msg="Stopping service" prefix=validator
time="2021-01-20 12:03:00" level=fatal msg="Wallet is not ready: context canceled" prefix=validator
```

A few tries later, container logs when stopping it (exit code 2)
```
time="2021-01-20 12:03:57" level=info msg="Got interrupt, shutting down..." prefix=node
time="2021-01-20 12:03:58" level=info msg="Stopping service" prefix=validator
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1113f82]

goroutine 186 [running]:
github.com/prysmaticlabs/prysm/shared/slotutil.(*SlotTicker).Done.func1(0x0)
	shared/slotutil/slotticker.go:37 +0x22
created by github.com/prysmaticlabs/prysm/shared/slotutil.(*SlotTicker).Done
	shared/slotutil/slotticker.go:36 +0x3f
```

In all cases the validator container does just fine when starting it again, works properly and logs show nothing strange:
```
time="2021-01-20 12:07:02" level=warning msg="Running on Pyrmont Testnet" prefix=flags
time="2021-01-20 12:07:02" level=warning msg="Enabled full web mode, wallet password will be written to disk at the wallet directory upon completing web onboarding." prefix=flags
time="2021-01-20 12:07:02" level=info msg="Enabling web portal to manage the validator client" prefix=node
time="2021-01-20 12:07:02" level=info msg="Checking DB" databasePath="/root/.eth2validators" prefix=node
time="2021-01-20 12:07:02" level=warning msg="You are using a non-default web host. Web traffic is served by HTTP, so be wary of changing this parameter if you are exposing this host to the Internet!" prefix=node web-host=0.0.0.0
time="2021-01-20 12:07:02" level=info msg="Starting Prysm web UI on address, open in browser to access" address="http://0.0.0.0:80" prefix=node
time="2021-01-20 12:07:02" level=info msg="Starting validator node" prefix=node version="Prysm/v1.1.0/9b367b36fc12ecf565ad649209aa2b5bba8c7797. Built at: 2021-01-18 19:47:14+00:00"
time="2021-01-20 12:07:02" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
time="2021-01-20 12:07:02" level=warning msg="You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: https://docs.prylabs.network/docs/prysm-usage/secure-grpc" prefix=validator
time="2021-01-20 12:07:02" level=info msg="gRPC server listening on address" address="0.0.0.0:7000" prefix=rpc
time="2021-01-20 12:07:02" level=info msg="Starting gRPC gateway" address="0.0.0.0:80" prefix=gateway
time="2021-01-20 12:07:32" level=warning msg="You are using the --web option but have not yet signed via a browser. If your web host and port are exposed to the Internet, someone else can attempt to sign up for you! You can visit http://0.0.0.0:80 to view the Prysm web interface" prefix=rpc
time="2021-01-20 12:08:02" level=warning msg="You are using the --web option but have not yet signed via a browser. If your web host and port are exposed to the Internet, someone else can attempt to sign up for you! You can visit http://0.0.0.0:80 to view the Prysm web interface" prefix=rpc
```

**Comment by eduadiez** [comment]
Could it be due to this?
```
You are using the --web option but have not yet signed via a browser.
```
Do you mind to try to reproduce it after adding the keys?

**Comment by dapplion** [comment]
> Do you mind to try to reproduce it after adding the keys?

Same result after adding the keys
